<?php

namespace App\db;

class AllProvinces
{
    public static array $arrProvinces  = array(
        array("nome" => "Agrigento", "sigla" => "AG", "regione" => "Sicilia"),
        array("nome" => "Alessandria", "sigla" => "AL", "regione" => "Piemonte"),
        array("nome" => "Ancona", "sigla" => "AN", "regione" => "Marche"),
        array("nome" => "Arezzo", "sigla" => "AR", "regione" => "Toscana"),
        array("nome" => "Ascoli Piceno", "sigla" => "AP", "regione" => "Marche"),
        array("nome" => "Asti", "sigla" => "AT", "regione" => "Piemonte"),
        array("nome" => "Avellino", "sigla" => "AV", "regione" => "Campania"),
        array("nome" => "Bari", "sigla" => "BA", "regione" => "Puglia"),
        array("nome" => "Barletta-Andria-Trani", "sigla" => "BT", "regione" => "Puglia"),
        array("nome" => "Belluno", "sigla" => "BL", "regione" => "Veneto"),
        array("nome" => "Benevento", "sigla" => "BN", "regione" => "Campania"),
        array("nome" => "Bergamo", "sigla" => "BG", "regione" => "Lombardia"),
        array("nome" => "Biella", "sigla" => "BI", "regione" => "Piemonte"),
        array("nome" => "Bologna", "sigla" => "BO", "regione" => "Emilia-Romagna"),
        array("nome" => "Bolzano/Bozen", "sigla" => "BZ", "regione" => "Trentino-Alto Adige/Südtirol"),
        array("nome" => "Brescia", "sigla" => "BS", "regione" => "Lombardia"),
        array("nome" => "Brindisi", "sigla" => "BR", "regione" => "Puglia"),
        array("nome" => "Cagliari", "sigla" => "CA", "regione" => "Sardegna"),
        array("nome" => "Caltanissetta", "sigla" => "CL", "regione" => "Sicilia"),
        array("nome" => "Campobasso", "sigla" => "CB", "regione" => "Molise"),
        array("nome" => "Carbonia-Iglesias", "sigla" => "CI", "regione" => "Sardegna"),
        array("nome" => "Caserta", "sigla" => "CE", "regione" => "Campania"),
        array("nome" => "Catania", "sigla" => "CT", "regione" => "Sicilia"),
        array("nome" => "Catanzaro", "sigla" => "CZ", "regione" => "Calabria"),
        array("nome" => "Chieti", "sigla" => "CH", "regione" => "Abruzzo"),
        array("nome" => "Como", "sigla" => "CO", "regione" => "Lombardia"),
        array("nome" => "Cosenza", "sigla" => "CS", "regione" => "Calabria"),
        array("nome" => "Cremona", "sigla" => "CR", "regione" => "Lombardia"),
        array("nome" => "Crotone", "sigla" => "KR", "regione" => "Calabria"),
        array("nome" => "Cuneo", "sigla" => "CN", "regione" => "Piemonte"),
        array("nome" => "Enna", "sigla" => "EN", "regione" => "Sicilia"),
        array("nome" => "Fermo", "sigla" => "FM", "regione" => "Marche"),
        array("nome" => "Ferrara", "sigla" => "FE", "regione" => "Emilia-Romagna"),
        array("nome" => "Firenze", "sigla" => "FI", "regione" => "Toscana"),
        array("nome" => "Foggia", "sigla" => "FG", "regione" => "Puglia"),
        array("nome" => "Forlì-Cesena", "sigla" => "FC", "regione" => "Emilia-Romagna"),
        array("nome" => "Frosinone", "sigla" => "FR", "regione" => "Lazio"),
        array("nome" => "Genova", "sigla" => "GE", "regione" => "Liguria"),
        array("nome" => "Gorizia", "sigla" => "GO", "regione" => "Friuli-Venezia Giulia"),
        array("nome" => "Grosseto", "sigla" => "GR", "regione" => "Toscana"),
        array("nome" => "Imperia", "sigla" => "IM", "regione" => "Liguria"),
        array("nome" => "Isernia", "sigla" => "IS", "regione" => "Molise"),
        array("nome" => "L'Aquila", "sigla" => "AQ", "regione" => "Abruzzo"),
        array("nome" => "La Spezia", "sigla" => "SP", "regione" => "Liguria"),
        array("nome" => "Latina", "sigla" => "LT", "regione" => "Lazio"),
        array("nome" => "Lecce", "sigla" => "LE", "regione" => "Puglia"),
        array("nome" => "Lecco", "sigla" => "LC", "regione" => "Lombardia"),
        array("nome" => "Livorno", "sigla" => "LI", "regione" => "Toscana"),
        array("nome" => "Lodi", "sigla" => "LO", "regione" => "Lombardia"),
        array("nome" => "Lucca", "sigla" => "LU", "regione" => "Toscana"),
        array("nome" => "Macerata", "sigla" => "MC", "regione" => "Marche"),
        array("nome" => "Mantova", "sigla" => "MN", "regione" => "Lombardia"),
        array("nome" => "Massa-Carrara", "sigla" => "MS", "regione" => "Toscana"),
        array("nome" => "Matera", "sigla" => "MT", "regione" => "Basilicata"),
        array("nome" => "Medio Campidano", "sigla" => "VS", "regione" => "Sardegna"),
        array("nome" => "Messina", "sigla" => "ME", "regione" => "Sicilia"),
        array("nome" => "Milano", "sigla" => "MI", "regione" => "Lombardia"),
        array("nome" => "Modena", "sigla" => "MO", "regione" => "Emilia-Romagna"),
        array("nome" => "Monza e della Brianza", "sigla" => "MB", "regione" => "Lombardia"),
        array("nome" => "Napoli", "sigla" => "NA", "regione" => "Campania"),
        array("nome" => "Novara", "sigla" => "NO", "regione" => "Piemonte"),
        array("nome" => "Nuoro", "sigla" => "NU", "regione" => "Sardegna"),
        array("nome" => "Ogliastra", "sigla" => "OG", "regione" => "Sardegna"),
        array("nome" => "Olbia-Tempio", "sigla" => "OT", "regione" => "Sardegna"),
        array("nome" => "Oristano", "sigla" => "OR", "regione" => "Sardegna"),
        array("nome" => "Padova", "sigla" => "PD", "regione" => "Veneto"),
        array("nome" => "Palermo", "sigla" => "PA", "regione" => "Sicilia"),
        array("nome" => "Parma", "sigla" => "PR", "regione" => "Emilia-Romagna"),
        array("nome" => "Pavia", "sigla" => "PV", "regione" => "Lombardia"),
        array("nome" => "Perugia", "sigla" => "PG", "regione" => "Umbria"),
        array("nome" => "Pesaro e Urbino", "sigla" => "PU", "regione" => "Marche"),
        array("nome" => "Pescara", "sigla" => "PE", "regione" => "Abruzzo"),
        array("nome" => "Piacenza", "sigla" => "PC", "regione" => "Emilia-Romagna"),
        array("nome" => "Pisa", "sigla" => "PI", "regione" => "Toscana"),
        array("nome" => "Pistoia", "sigla" => "PT", "regione" => "Toscana"),
        array("nome" => "Pordenone", "sigla" => "PN", "regione" => "Friuli-Venezia Giulia"),
        array("nome" => "Potenza", "sigla" => "PZ", "regione" => "Basilicata"),
        array("nome" => "Prato", "sigla" => "PO", "regione" => "Toscana"),
        array("nome" => "Ragusa", "sigla" => "RG", "regione" => "Sicilia"),
        array("nome" => "Ravenna", "sigla" => "RA", "regione" => "Emilia-Romagna"),
        array("nome" => "Reggio di Calabria", "sigla" => "RC", "regione" => "Calabria"),
        array("nome" => "Reggio nell'Emilia", "sigla" => "RE", "regione" => "Emilia-Romagna"),
        array("nome" => "Rieti", "sigla" => "RI", "regione" => "Lazio"),
        array("nome" => "Rimini", "sigla" => "RN", "regione" => "Emilia-Romagna"),
        array("nome" => "Roma", "sigla" => "RM", "regione" => "Lazio"),
        array("nome" => "Rovigo", "sigla" => "RO", "regione" => "Veneto"),
        array("nome" => "Salerno", "sigla" => "SA", "regione" => "Campania"),
        array("nome" => "Sassari", "sigla" => "SS", "regione" => "Sardegna"),
        array("nome" => "Savona", "sigla" => "SV", "regione" => "Liguria"),
        array("nome" => "Siena", "sigla" => "SI", "regione" => "Toscana"),
        array("nome" => "Siracusa", "sigla" => "SR", "regione" => "Sicilia"),
        array("nome" => "Sondrio", "sigla" => "SO", "regione" => "Lombardia"),
        array("nome" => "Taranto", "sigla" => "TA", "regione" => "Puglia"),
        array("nome" => "Teramo", "sigla" => "TE", "regione" => "Abruzzo"),
        array("nome" => "Terni", "sigla" => "TR", "regione" => "Umbria"),
        array("nome" => "Torino", "sigla" => "TO", "regione" => "Piemonte"),
        array("nome" => "Trapani", "sigla" => "TP", "regione" => "Sicilia"),
        array("nome" => "Trento", "sigla" => "TN", "regione" => "Trentino-Alto Adige/Südtirol"),
        array("nome" => "Treviso", "sigla" => "TV", "regione" => "Veneto"),
        array("nome" => "Trieste", "sigla" => "TS", "regione" => "Friuli-Venezia Giulia"),
        array("nome" => "Udine", "sigla" => "UD", "regione" => "Friuli-Venezia Giulia"),
        array("nome" => "Valle d'Aosta/Vallée d'Aoste", "sigla" => "AO", "regione" => "Valle d'Aosta/Vallée d'Aoste"),
        array("nome" => "Varese", "sigla" => "VA", "regione" => "Lombardia"),
        array("nome" => "Venezia", "sigla" => "VE", "regione" => "Veneto"),
        array("nome" => "Verbano-Cusio-Ossola", "sigla" => "VB", "regione" => "Piemonte"),
        array("nome" => "Vercelli", "sigla" => "VC", "regione" => "Piemonte"),
        array("nome" => "Verona", "sigla" => "VR", "regione" => "Veneto"),
        array("nome" => "Vibo Valentia", "sigla" => "VV", "regione" => "Calabria"),
        array("nome" => "Vicenza", "sigla" => "VI", "regione" => "Veneto"),
        array("nome" => "Viterbo", "sigla" => "VT", "regione" => "Lazio")
    );
}